### ISSUE TITLE
Read C_Cpp.clang_format_fallbackStyle from VS Code setting for clang-format

### ISSUE THREAD

**Issue by rongxin-liu** [cs50/style50.vsix#2]

**Comment by dmalan** [comment]
Actually, ideally, we should probably have `style50` mimic VS Code's own behavior?

> By default, the clang-format style is set to "file" which means it looks for a .clang-format file inside your workspace. If the .clang-format file is found, formatting is applied according to the settings specified in the file. If no .clang-format file is found in your workspace, formatting is applied based on a default style specified in the C_Cpp.clang_format_fallbackStyle setting instead. Currently, the default formatting style is "Visual Studio" which is an approximation of the default code formatter in Visual Studio.

Cf. https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting.

**Comment by rongxin-liu** [comment]
That's even better!
https://github.com/cs50/style50.vsix/commit/aed525dc31f550938a233a7198aad06801490583
