### ISSUE TITLE
style50 in vscode does not tell you to add curly brackets but it is required for a full style50 score

### ISSUE THREAD

**Issue by 3m4r5** [cs50/style50.vsix#5]
for example, the following code:
```c
if (true)
    int x;
```
does not trigger a warning or anything even though it will not get a full score.

**Comment by rongxin-liu** [comment]
style50 CLI use astyle, which has different requirements. Does that prevent you from getting a passing score for your pset?

**Comment by 3m4r5** [comment]
no, the lowest I got until now is 0.82
