### ISSUE TITLE
Doesn't format a file without `main`

### ISSUE THREAD

**Issue by dmalan** [cs50/style50.vsix#6]
E.g., this should compile with `clang -c`:

```
#include <stdio.h>

#define LENGTH 46

typedef struct node
{
    char word[LENGTH + 1];
    struct node *next;
} node;
```

But extension errs with:

<img width="458" alt="Screenshot 2023-09-17 at 10 15 29 AM" src="https://github.com/cs50/style50.vsix/assets/788678/3c7512e2-51d7-4eac-af39-9b16b8213a77">

**Comment by rongxin-liu** [comment]
This is not a bug I'm afraid, that's just how `clang -fsyntax-only` works.

**Comment by dmalan** [comment]
Hm, might have been user error on my part. Seems to work as expected, actually.
