### ISSUE TITLE
Clicking `style50` button multiple times yields multiple tabs, which reveal temporary filenames

### ISSUE THREAD

**Issue by dmalan** [cs50/style50.vsix#7]
Better to treat style50 tab as a singleton and re-use it if already open?

<img width="975" alt="Screenshot 2023-09-17 at 10 19 16 AM" src="https://github.com/cs50/style50.vsix/assets/788678/a0f9f2c8-cb90-435b-8d24-28407e5dc3a8">

**Comment by rongxin-liu** [comment]
Let me revisit this again, I have been struggled to close a text editor programmatically because there isn't a way to do it.

**Comment by dmalan** [comment]
Can we just reload its contents perhaps?

**Comment by dmalan** [comment]
@rongxin-liu I think this one is fixed?

**Comment by rongxin-liu** [comment]
Yes, we can close this one.
